import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import My3DScene from "@/components/My3DScene";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex h-screen w-full bg-black">
          {/* Sidebar for sm+ screens only */}
          <aside className="hidden sm:flex w-[35%] items-center justify-center overflow-hidden bg-black">
            <div className="scale-[0.55]">
              <My3DScene width="950px" height="1000" />
            </div>
            <div className=""></div>
          </aside>



          {/* Main content takes full width on small screens */}
          <main className="w-full sm:w-[65%] p-4 overflow-y-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
