// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProjectCardCarousel from "@/components/ProjectCardCarousel";
import { projects } from "@/constants/projectDetails"; // Import your projects from constants

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex h-screen w-full bg-[#141312]">
          {/* Sidebar for sm+ screens only */}
          <aside className="hidden sm:block fixed left-0 top-0 h-screen w-[35%] bg-[#141312] z-10">
            <ProjectCardCarousel projects={projects} />
          </aside>

          <main className="w-full sm:ml-[35%] overflow-y-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}