import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import My3DScene from "@/components/My3DScene";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex h-screen w-full bg-black">
          {/* Sidebar for sm+ screens only */}
          <aside className="hidden sm:block fixed left-0 top-0 h-screen w-[35%] bg-black z-10">
            <div className="relative h-full flex flex-col items-center justify-center">
              
              {/* Black overlay container */}
              {/* <div className="absolute bottom-[204px] left-[381px] w-16 h-[17px] bg-green-500 z-20" /> */}
              
              {/* Sidebar content below overlay */}
              <div className="z-10  text-white">
                {/* <h2 className="text-xl mb-4">Check this out baby</h2> */}

                <div className="scale-[0.55]">
                  <My3DScene width="850px" height="1000"   />
                </div>
              </div>
            </div>
          </aside>


          <main className="w-full sm:ml-[35%] p-4 overflow-y-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
